### ISSUE TITLE
Handle foreign key automatically

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-django#13]
Might be the same as #2

**Comment by dethi** [comment]
Yep. The problem is to detect that it is a foreign key. I'm still investigating the Django's core to find a way to do it.

**Comment by dethi** [comment]
Is it a request from a customer?

**Comment by maxiloc** [comment]
yep

**Comment by arnaudlimbourg** [comment]
Starting in Django 1.8 you have the [Meta API](https://docs.djangoproject.com/en/1.8/ref/models/meta/). My understanding is you could use ``MyModel._meta.get_field(name)`` to find more info about the field.

In previous Django versions you have to use the [old api](https://docs.djangoproject.com/en/1.8/ref/models/meta/#django.db.models.options.Options.get_field) but the documentation explains it better than I would.

**Comment by cabello** [comment]
Yes, I recommend using the Meta API for Django 1.8, `get_fields` will return all model fields, and `is_relation` property will tell you if it's a foreign key.

**Comment by jdotjdot** [comment]
I think this is the same as this issue and #2--I'm not even able to get through the installation instructions in the README because the first time I run `python manage.py algolia_reindex`, I get a `KeyError` that looks like it's due to trying to call a `RelatedManager` (from a `ForeignKey`) simply because it's callable:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/contrib/algoliasearch/management/commands/algolia_reindex.py", line 22, in handle
    batch_size=options.get('batchsize', None))
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/contrib/algoliasearch/models.py", line 224, in reindex_all
    batch.append(self._build_object(instance))
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/contrib/algoliasearch/models.py", line 149, in _build_object
    attr = attr()
  File "/Users/JJ/.virtualenvs/TCJ/lib/python2.7/site-packages/django/db/models/fields/related.py", line 654, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u'manager'
```

The `attr` in question that is being called is the reverse `RelatedManager` for a related model with a foreign key on my model.

If I could declare attributes in the `AlgoliaIndex` class that would let me override and specify how I want to handle certain fields, similar to how you can in Django Rest Framework serializers, that would probably do the trick here.  I may do this by subclassing `AlgoliaIndex` and rewriting my own `_build_object()` method, or by just using DRF serializers and bypassing algoliasearch-django entirely (as much as I'd like to use it).

**Comment by dethi** [comment]
Hey @jdotjdot,
Your issue certainly comes from this [line](https://github.com/algolia/algoliasearch-django/blob/master/src/models.py#L48). I think you can fix it by creating a "model index" with the `fields` defined to what you really need to index (take a look at the end of the Quick Start).

There is a lot of bugs fix and new features in the `develop` branch that need documentation. I will try to do it as soon as I have some free time! I'm sorry for the long waiting time :disappointed:

**Comment by thetylerhayes** [comment]
Just wanted to say I was able to get this working thanks to @dethi's comment ^^ but I'll also throw my hat in the ring that it was frustrating when I was setting this up and thinking I'd get up and running quickly and having a roadblock pretty much immediately in the form of an ambiguous exception I then had to Google. :) Thanks for making a great product overall though!

**Comment by calitidexvii** [comment]
Is there a workaround to include fields from the ForeignKey model within the index? For example, using @thetylerhayes model:

`class CommentIndex(AlgoliaIndex):
    fields = ('user.first_name', 'raw_message')`

**Comment by dethi** [comment]
Hi @calitidexvii 
Not for now sorry. The issue is that during object update, these fields are not necessary available and will need to be fetched from the database.

**Comment by calitidexvii** [comment]
Thanks @dethi 
Based on your research, do you think it's something that could be added if you had the help? For example:

```
class CommentIndex(AlgoliaIndex):
    fields = ('raw_message')
    fk_fields = ('user.first_name')
```

Where fk_fields would perform the DB lookup and append to the object?

**Comment by calitidexvii** [comment]
For anyone else needing a workaround, I was able to use callables within the model for the index.

```
class Comment(models.Model):
    user = models.ForeignKey(User)
    raw_message = models.TextField()

    def user_filter(self):
        return [self.user.username]
```

Then the index:

```
class CommentIndex(AlgoliaIndex):
    fields = ('raw_message')
    tags = 'user_filter'
```

This isn't perfect and may not work in all situations, but it seems to be sufficient when you need to manage user access with [secured API keys](https://www.algolia.com/doc/python#security--user-api-keys).

**Comment by abendig** [comment]
Would love to hear if there is any news as to when this might be available -- or how best to help make this a reality.

This is an increasingly important use case for us. One example: Indexing User profile data, where some information may be in the User table and other information is in a UserProfile table.

**Comment by calitidexvii** [comment]
@abendig Due to the issue @dethi mentioned, I don't think there are any plans to extend the integration to handle relations.

Do you have a working solution? If not, you could try my workaround above - using callables to get the necessary data. Due to increasingly complex relations, I ultimately ended up dumping the Django integration and writing custom methods using only the Python integration. If you need some direction, let me know.

If you need/want the management functions of the Django integration, it may be worth forking and extending AlgoliaIndex to make the [database calls for relations](https://github.com/algolia/algoliasearch-django/issues/13#issuecomment-213595214) (caveat emptor).

**Comment by calitidexvii** [comment]
@abendig I just noticed, this was added to the [2.0.0 milestone](https://github.com/algolia/algoliasearch-django/milestone/2) in June 2016, but I don't see a timeline for it.

**Comment by dethi** [comment]
Hi,
Sorry. I don't work anymore at Algolia so it's only a side project for me. 
The milestone 2.0.0 has a due date, end of October, and I will fulfil it in time.
I hope it won't be too late for you!

**Comment by abendig** [comment]
Thanks a lot for the update. I do need to make this functionality work one way or another in the next couple weeks. How far along is this particular feature? Is it possible/useful to get involved in some way to drive the development of this forward?

**Comment by dethi** [comment]
I would appreciate if you could provide me a django app that fakes your use case.

**Comment by PLNech** [comment]
Closed as stale without an answer from OP.

**Comment by PLNech** [comment]
For future readers, the readme now contains a [section on indexing relations](https://github.com/algolia/algoliasearch-django#field-preprocessing-and-related-objects).
