### ISSUE TITLE
Handle multiple geolocations

### ISSUE THREAD

**Issue by m-vdb** [algolia/algoliasearch-django#146]
Hi there,

It looks like this SDK doesn't support multiple geolocations whereas the API does. [The code](https://github.com/algolia/algoliasearch-django/blob/master/src/models.py#L155-L159) wouldn't be too difficult to adapt, something like that would work:
```python
def _validate_geoloc(geo):
    assert set(geo) == {'lat', 'lng'}, 'Invalid geolocation format, requires "lat" and "lng" keys, only.'
if isinstance(loc, tuple):
    tmp['_geoloc'] = {'lat': loc[0], 'lng': loc[1]}
elif isinstance(loc, dict):
    _validate_geoloc(loc)
    tmp['_geoloc'] = loc
elif isinstance(loc, list):
    [_validate_geoloc(geo) for geo in loc]
    tmp['_geoloc'] = loc
```

Do you accept PRs for this project?

**Comment by redox** [comment]
> It looks like this SDK doesn't support multiple geolocations whereas the API does. The code wouldn't be too difficult to adapt, something like that would work:

Ah yes good point, this is something we've added later on and never updated the django lib.

> Do you accept PRs for this project?

Yes, and I'll be happy to merge it 👍

**Comment by m-vdb** [comment]
ok i'll work on it today or tomorrow then, thanks!
