### ISSUE TITLE
Add support for non-callable for should_index attribute

### ISSUE THREAD

**Issue by m-vdb** [algolia/algoliasearch-django#147]
Hi there,

I think it would be more convenient to handle both callable and non-callable attributes on the model instance. For example, I have a model field that is a boolean and I would like to use its value for the `should_index` parameter. I think it wouldn't be too hard too do. Would you be open to the idea?

(Note: this can be done easily for the `should_index` parameter, and given your `AlgoliaIndex` class design it shouldn't be too hard to have this for all parameters 🎉)

Edit: I just saw that you already support non-callable attributes [here](https://github.com/algolia/algoliasearch-django/blob/master/src/models.py#L154-L165), so this issue only concerns `should_index`

**Comment by m-vdb** [comment]
what do you think @PLNech ?

**Comment by PLNech** [comment]
Hey @m-vdb, thank you for your feedback. 
Indeed supporting non-callable attributes on `should_index` should be easy, I'm on it 🙂
