### ISSUE TITLE
support for setting_changed while testing

### ISSUE THREAD

**Issue by ornoone** [algolia/algoliasearch-django#169]
the AlgoliaEngine use the current settings at import time to build the «algolia_engine» global variable. 

the problem is that while testing, we can require to stop the auto indexing for a given test with somthing like this : 

```python
    @override_settings(ALGOLIA={
        'APPLICATION_ID': 'bépo',
        'API_KEY': 'bépo',
        'AUTO_INDEXING': False
    })
    def test_extensive_function(self):
        assert somthing
```

in the current version, the `override_settings` has absolutly no effect and the client is not updated nor the post_save and post_delete signals is removed. 

to use algoliasearch-django in some tests, i must do something like 
```python
from django.apps import AppConfig
from django.apps.registry import apps

class MyAppConfig(AppConfig):

    def reset_agolia_engin(self, *args, **kwargs):
        algolia_engine.unregister(apps.get_model('my_app', 'MyModel'))
        algolia_engine.__init__()  # reset client using new params
        algolia_engine.register(apps.get_model('my_app', 'MyModel'), MyModelIndex)

    def ready(self):
        setting_changed.connect(self.reset_agolia_engin)
```

**Comment by PLNech** [comment]
Hi @ornoone, thank you for this feedback!
I didn't know about Django's `override_settings`, let me have a look at it and see how we could leverage it in Algolia to make your testing simpler 🙂

**Comment by PLNech** [comment]
Since [`v1.4.0`](https://github.com/algolia/algoliasearch-django/releases/tag/1.4.0), you can use [`self.settings()`](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.SimpleTestCase.settings) to override settings:

```python
class OverrideSettingsTestCase(TestCase):
    def setUp(self):
        with self.settings(ALGOLIA={
            'APPLICATION_ID': 'foo',
            'API_KEY': 'bar',
            'AUTO_INDEXING': False
        }):
            algolia_engine.reset(settings.ALGOLIA)

    def tearDown(self):
        algolia_engine.reset(settings.ALGOLIA)

    def test_foo():
        # ...
```
