### ISSUE TITLE
Allow specific models to be reindexed

### ISSUE THREAD

**Issue by birakattack** [algolia/algoliasearch-django#19]
- Currently all models have to be synced everytime `python manage.py algolia_reindex` is called. 
- I would like to be able to make the following call: `python manage.py algolia_reindex <MODEL_NAME>` such that only the model passed will be reindexed with Algolia

**Comment by arnaudlimbourg** [comment]
@birakattack you can pass the ``--model`` parameter.

In the code there is:
```python
parser.add_argument('--model', nargs='+', type=str)
```

**Comment by dethi** [comment]
:+1: just need to document it (too much hidden features in this project :disappointed:)

**Comment by arnaudlimbourg** [comment]
Added to #20

**Comment by birakattack** [comment]
Running the command `python manage.py algolia_reindex --model <MODEL_NAME>` fails with the response:
```
Usage: manage.py algolia_reindex [options]

Reindex all models to Algolia

manage.py: error: no such option: --model
```

I am using version `algoliasearch-django==1.2.3`

Am I doing something wrong?

**Comment by dethi** [comment]
Which version of Python? Django?
With Python2.7 and Django 1.9.2, it works:

```
Reindex all models to Algolia

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Verbosity level; 0=minimal output, 1=normal output,
                        2=verbose output, 3=very verbose output
  --settings SETTINGS   The Python path to a settings module, e.g.
                        "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be
                        used.
  --pythonpath PYTHONPATH
                        A directory to add to the Python path, e.g.
                        "/home/djangoprojects/myproject".
  --traceback           Raise on CommandError exceptions
  --no-color            Don't colorize the command output.
  --batchsize [BATCHSIZE]
  --model MODEL [MODEL ...]
```

**Comment by birakattack** [comment]
I am using python 2.7.9, however, I believe its my django version (1.7) is causing the issue. 

Thank you so much for following up I really appreciate it!

I'm going to close the issue now.

**Comment by dethi** [comment]
Strange, normally we are supporting Django 1.7+. I will investigate..

**Comment by birakattack** [comment]
Thanks very much!!

**Comment by dethi** [comment]
Django changed in 1.8 the way it manages arguments for custom admin command. I don't really see a clean way to support the old and new way. Django 1.7 is deprecated, so I don't really want to hack something for an old version.
Sorry, but I think you will have to update to at least Django 1.8.

**Comment by PLNech** [comment]
Closed as `wontfix`.
