### ISSUE TITLE
Add the option `disable_indexing`

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-django#209]
In the rails integration it's possible to disable_indexing for certain env: https://www.algolia.com/doc/api-client/rails/testing/

Could it be possible to have the same for django?

**Comment by PLNech** [comment]
Thanks for the report, I'll see if it is possible!

**Comment by PLNech** [comment]
Since [`v1.4.0`](https://github.com/algolia/algoliasearch-django/releases/tag/1.4.0), you can use [`self.settings()`](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.SimpleTestCase.settings) to disable indexing:

```python
# For a single test
def test_no_indexing():
    with self.settings(ALGOLIA={
        'AUTO_INDEXING': False
    }):
        algolia_engine.reset(settings.ALGOLIA)
        # YOUR TEST CODE HERE
    algolia_engine.reset(settings.ALGOLIA)


# For a whole TestCase
class NoIndexinxTestCase(TestCase):
    def setUp(self):
        with self.settings(ALGOLIA={
            'AUTO_INDEXING': False
        }):
            algolia_engine.reset(settings.ALGOLIA)

    def tearDown(self):
        algolia_engine.reset(settings.ALGOLIA)

    def test_foo():
        # ...
```
