### ISSUE TITLE
Ability to configure replicas

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-django#21]
In the `rails` integration, we can define the replicas configuration inside the `algoliasearch` configuration block. Would be great to have the same.

**Comment by PLNech** [comment]
Hey @redox, today you can define replicas for each index as such:
```
        class WebsiteIndex(AlgoliaIndex):
            settings = {
                'replicas': [
                    index.index_name + '_name_asc',
                    index.index_name + '_name_desc'
                ]
            }
```
Is this what you are looking for? I'm not sure what you mean by "`algoliasearch` configuration block". 

If you are you talking about the `settings.ALGOLIA` configuration block, I don't understand what you expect with replicas defined for any index. Unless you mean a global replica suffix?  🤔

**Comment by PLNech** [comment]
_Closing in absence of a reply, feel free to reopen the issue if you have something to add._
