### ISSUE TITLE
Problem in generating API key.

### ISSUE THREAD

**Issue by neeti25** [algolia/algoliasearch-django#212]
I tried registering me models to Algoliasearch and i get this traceback:

`(venv)tas@tas-System-Product-Name:~/projects/schoolmgmt/mysite$ python manage.py algolia_reindexTraceback (most recent call last):  File "manage.py", line 22, in     execute_from_command_line(sys.argv)  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line    utility.execute()  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute    django.setup()  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup    apps.populate(settings.INSTALLED_APPS)  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate    app_config = AppConfig.create(entry)  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create    module = import_module(entry)  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module    __import__(name)  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/algoliasearch_django/__init__.py", line 7, in     from . import registration  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/algoliasearch_django/registration.py", line 189, in     algolia_engine = AlgoliaEngine()  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/algoliasearch_django/registration.py", line 38, in _init_    self.client = algoliasearch.Client(app_id, api_key)  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/algoliasearch/client.py", line 89, in _init_    self.api_key = api_key  File "/home/tas/projects/schoolmgmt/venv/local/lib/python2.7/site-packages/algoliasearch/client.py", line 122, in api_key    if len(value) > MAX_API_KEY_LENGTH:TypeError: object of type 'NoneType'`

Apparently there is no API key generated. How do i generate one? I tried this code in mysite/settings.py:
`ALGOLIA = {
    'APPLICATION_ID': os.getenv('ALGOLIA_APPLICATION_ID'),
    'API_KEY': os.getenv('ALGOLIA_API_KEY'),
    'AUTO_INDEXING' : True,
    'SEARCH_API_KEY': os.getenv('ALGOLIA_SEARCH_API_KEY'),
}`
Please help.

**Comment by PLNech** [comment]
Hi @neeti25, you can find your api keys in your [Algolia dashboard](https://www.algolia.com/api-keys).
