### ISSUE TITLE
algolia_reindex not found

### ISSUE THREAD

**Issue by imdiegoestevez** [algolia/algoliasearch-django#222]
Hi!
For some reason none of the algolia commands are recognized by django (at least in my computer). I have django 1.11, python 3.5.2, algoliasearch installed, algoliasearch-django installed. 
Do you have any clue how to fix this?
`python manage.py algolia_reindex
Unknown command: 'algolia_reindex'
Type 'manage.py help' for usage.
`

**Comment by Haroenv** [comment]
Hey @imdiegoestevez, could you create a repository where we can see this issue? It’s pretty tough to debug an issue like this without having the same setup

**Comment by PLNech** [comment]
Hi @imdiegoestevez, can you reproduce this with [algolia/algoliasearch-django-example](https://github.com/algolia/algoliasearch-django-example)? Just follow the [README's steps](https://github.com/algolia/algoliasearch-django-example#dependencies) and let us know if the same issue happens :)

**Comment by arnaudlimbourg** [comment]
@imdiegoestevez without more info it is difficult but I would look into `INSTALLED_APPS`, does it contain `'algoliasearch_django'`?

**Comment by imdiegoestevez** [comment]
I was missing `'algoliasearch_django'` in `INSTALLED_APPS`. Thank you all very much for helping and big thanks to @arnaudlimbourg
