### ISSUE TITLE
Tags has same value for each item in index

### ISSUE THREAD

**Issue by qcaron** [algolia/algoliasearch-django#228]
I provide a callable for the index' tags but it seems the tag value is only computed once. Indeed, when checking my index in Algolia admin, all items have the same tags (which is 1 item).

I am using Python 2.7.10 and Django 1.8.4 with algoliasearch==1.14.1 and algoliasearch-django==1.5.1.

Here is my code:

    # models.py

    class JobOffer(models.Model):
        reference_code = models.ForeignKey(
            ReferenceCode,
           blank=True,
            null=True,
            verbose_name=_(u"Code de référence"),
        )

        def reference_code_value(self):
            if self.reference_code:
                return [self.reference_code.value]  # value is a CharField in the ReferenceCode model
            return ['NONE']

    # Index

    class JobOfferIndex(AlgoliaIndex):
        tags = 'reference_code_value'

Am I misusing the Algolia tags or is my code not correct?

**Comment by qcaron** [comment]
That was quick! I found the issue: it lies in algoliasearch_django.models.AlgoliaIndex.get_raw_record:

            if self.tags:
                if callable(self.tags):
                    self.tags = self.tags(instance)
                if not isinstance(self.tags, list):
                    self.tags = list(self.tags)
                tmp['_tags'] = self.tags

should be 

            if self.tags:
                if callable(self.tags):
                    tmp['_tags'] = self.tags(instance)
                if not isinstance(tmp['_tags'], list):
                    tmp['_tags'] = list(tmp['_tags'])

Should I do a pull request then or can you update that straight away? Thanks guys!

**Comment by PLNech** [comment]
Hi @qcaron, thanks for reporting this issue!

You're right about the source of the issue. It's up to you, I can do the change on my own or let you PR if you want the credit for this contribution! In this case, please send it with a test in `test_indexing.py` and I'll be happy to review it 😉

**Comment by qcaron** [comment]
I am willing to do a PR but I have an error with the tests: 

    AlgoliaException: Index test_User_django does not exist

I manually created this index in my Algolia Dashboard but it did not change anything. Do you have any clue what is going on?

**Comment by PLNech** [comment]
Hi @qcaron, glad to have you contributing :)

This is surprising, you should not have to create anything. Checking out the code in `master` and running `tox` works for me:

```
tox                                                                                                                                18:16:34  ☁  pr/qcaron ☀
GLOB sdist-make: /Users/pln/Work/APIClients/algoliasearch-django/setup.py
py27-django17 inst-nodeps: /Users/pln/Work/APIClients/algoliasearch-django/.tox/dist/algoliasearch-django-1.5.1.zip
py27-django17 installed: algoliasearch==1.14.1,algoliasearch-django==1.5.1,asn1crypto==0.23.0,certifi==2017.11.5,cffi==1.11.2,chardet==3.0.4,cryptography==2.1.3,Django==1.7.11,enum34==1.1.6,idna==2.6,ipaddress==1.0.18,pycparser==2.18,pyOpenSSL==17.3.0,requests==2.18.4,six==1.11.0,urllib3==1.22
py27-django17 runtests: PYTHONHASHSEED='301447057'
py27-django17 runtests: commands[0] | python runtests.py
Creating test database for alias 'default'...
.................................................
----------------------------------------------------------------------
Ran 49 tests in 38.549s

OK
```

Could you push your code in your fork so I can see if it's related to your changes?

You can also check [your dashboard](https://www.algolia.com/apps/dashboard)'s `Latest Operations` section to check the order of calls (the testsuite should create this index, run tests on it, then delete it)

**Comment by qcaron** [comment]
Sorry for the delay, I had to deliver by fixing code in site-packages (shame on me).

I created a second user in the setUp method. I would then like to get the records in the index (there should be two now) but calling `index.raw_search()` produces the error. Any idea how can I check tags for all records in the index?

**Comment by qcaron** [comment]
@PLNech It turned out that using only `raw_search` was not useful to fulfill the tests.

Leaving `models.AlgoliaIndex.get_raw_record` as-is made the tests fail. After I made my changes to it, tests did not give an error anymore. It is using `get_raw_record` on a second test User. 

I will do the pull request in a couple of minutes. 

Thanks for your help!

**Comment by PLNech** [comment]
@qcaron sorry for the delay in my replying, you were right to use `get_raw_record` directly! I'm reviewing the PR now 🙂

**Comment by qcaron** [comment]
@PLNech Nice! Thank you!
