### ISSUE TITLE
Multiple models in same index won't work

### ISSUE THREAD

**Issue by phoebebright** [algolia/algoliasearch-django#23]
I have decided to put all my models into one index and have added an attribute, modelname:

```
@property
def modelname(self):
    return self._meta.model_name
```

This works fine for automatic updates but using the management command I'm finding that the index is cleared between models regardless of whether I use a straight reindex or reindex --model as reindex clears the existing index first.

Is it possible to do a reindex without a clear first?

**Comment by dethi** [comment]
Not yet, but I will think about it. The next release is planned for this summer.

**Comment by phoebebright** [comment]
Thought I could be clever and add this hack as a temporary fix, but doesn't seem to make a difference, still overwritting with each model.  Do you have any quick hackish solution to this?


    def reindex_all(self, batch_size=1000):
        '''Reindex all records.'''
        if self.settings:
            self.__tmp_index.set_settings(self.settings)
            logger.debug('APPLY SETTINGS ON %s_tmp', self.index_name)
        
        #PHB removing this as quick hack to use in tc with multiple models in same index
        #self.__tmp_index.clear_index()
        #logger.debug('CLEAR INDEX %s_tmp', self.index_name)

        result = None
        counts = 0
        batch = []

**Comment by dethi** [comment]
This doesn't work because it clears the temporary index. Indeed, the process of reindexing is as follow:
- clean a temporary index, "%s_tmp" % index_name
- push all records to the temporary index
- move the temporary index to the index (override)

By doing this way, there is no downtime for all search during the reindexing.

If you don't care about this, you can replace the function with this one:

```python
def reindex_all(self, batch_size=1000):
    '''Reindex all records.'''
    if self.settings:
        self.__index.set_settings(self.settings)
        logger.debug('APPLY SETTINGS ON %s', self.index_name)

    result = None
    counts = 0
    batch = []

    if hasattr(self, 'get_queryset'):
        qs = self.get_queryset()
    else:
        qs = self.model.objects.all()

    for instance in qs:
        if self.should_index:
            if not self.should_index(instance):
                continue  # should not index

        batch.append(self._build_object(instance))
        if len(batch) >= batch_size:
            result = self.__index.save_objects(batch)
            logger.info('SAVE %d OBJECTS TO %s', len(batch),
                        self.index_name)
            batch = []
        counts += 1
    if len(batch) > 0:
        result = self.__index.save_objects(batch)
        logger.info('SAVE %d OBJECTS TO %s', len(batch),
                    self.index_name)

    return counts
```

This will reindex all records without temporary index, and without cleaning the index.

**Comment by phoebebright** [comment]
Perfect.  Thank you.

**Comment by phoebebright** [comment]
Did a bit of playing around and added an -noclear option in this commit: https://github.com/phoebebright/algoliasearch-django/commit/b20b73fb10500b8ae701618ee7bef011aab2a85d

However, not sure of the implications of doing this if you want multiple index...

**Comment by PLNech** [comment]
As of today we do not recommend to put objects structured differently in the same index, so I'll close this feature request.

@phoebebright: if the workaround mentioned does not work for you and you still would like such a feature, feel free to reopen this!
