### ISSUE TITLE
Multiple indexes for the same Model

### ISSUE THREAD

**Issue by Ignipro** [algolia/algoliasearch-django#24]
Hi, I'm trying to build a search feature with two type of permissions on the model fields... Is there a way to index the same Model with multiple indexes (in which I specify the configuration hence the field to show and to index) ?

When I define

```
class MyAppConfig(AppConfig):
    name = 'my_model'
    def ready(self):
        MyModel = self.get_model('MyModel')
        algoliasearch.register(MyModel, MyModelIndex1)
        algoliasearch.register(MyModel, MyModelIndex2)
```

I get  `RegistrationError: <class 'my_app.models.MyModel'> is already registered with Algolia engine`

**Comment by dethi** [comment]
Hello,

It's not possible (because of this https://github.com/algolia/algoliasearch-django/blob/master/src/registration.py#L46-L48) and, unfortunately, I have no work around for you in mind... 😞 

I will try to find a solution for the next release.

**Comment by dethi** [comment]
But maybe your use case can be resolved by using several API keys with specific security settings. If you need help, don't hesitate!

**Comment by Ignipro** [comment]
@dethi Yes I would really appreciate a little help :) Do you mean that by using several API keys on the same index with specific security settings, I can configure which field will be viewable or indexed depending of the user (i.e. the api key). Thanks a lot !

**Comment by dethi** [comment]
Not exactly but you can filter viewable records: https://www.algolia.com/doc/guides/security/api-keys#how-it-works and https://www.algolia.com/doc/api-client/python/api-keys#generate-key

But I don't know if it's enough for you, let me know!

**Comment by Ignipro** [comment]
Thanks for response ! First I also thought about filtering records but it doesn't really apply in my case since the instance viewable/searchable by the two type of users are the same. I just want to specify which field they have access to. Maybe I could use the filtering tricks and register each object instance two times on Algolia (with field values transformed as property equals to the value or null depending of the user type tag). Seems a little complicated thought... Do you think it would take long for me to  enhance the lib with a model multiple indexation feature ? (Didn't really had time yet to have a further look at the code) I would then send you a pull request.

**Comment by dethi** [comment]
Currently, the register class rely heavily on the fact that one model can only be registered one time. I think it will need a lot of rethinking to fix the issue.

However I just found a good solution, that I think is the right way to do it.

You need to create and register a `MetaIndexModel` that delegates work to others `IndexModel`, instead of registering your two `IndexModel`. See below for an example.

```python
from django.contrib.algoliasearch import AlgoliaIndex


class MyModelIndex1(AlgoliaIndex):
	name = 'MyModelIndex1'
	...


class MyModelIndex2(AlgoliaIndex):
	name = 'MyModelIndex2'
	...


class MyMetaModelIndex(AlgoliaIndex):
	model_index = []

	def __init__(Self, model, client):
		self.model_index = [
			MyModelIndex1(model, client),
			MyModelIndex2(model, client)
		]
		
	def update_obj_index(self, instance):
		for indexer in model_index:
			indexer.update_obj_index(instance)
		
	def def delete_obj_index(self, instance):
		for indexer in model_index:
			indexer.delete_obj_index(instance)
		
	def raw_search(self, query='', params={}):
		res = {}
		for indexer in model_index:
			res[indexer.name] = indexer.raw_search(query, params)
		return res
		
	def set_settings(self):
		for indexer in model_index:
			indexer.set_settings()
		
	def clear_index(self):
		for indexer in model_index:
			indexer.clear_index()
	 
	def reindex_all(self, batch_size=1000):
		for indexer in model_index:
			indexer.reindex_all(batch_size)
```

and:

```python
algoliasearch.register(MyModel, MyMetaModelIndex)
```

**Comment by dethi** [comment]
With this solution, you can:
- index a model in multiple index
- route model to a specific index based on your own rules
- etc

**Comment by Ignipro** [comment]
Thanks @dethi :) this is exactly what I was looking for and it works perfectly ! If others want to use this feature, you will find below the same code with just some typo mistakes corrected :  

1) First define all your indexes that will work on the same model :
```
from django.contrib.algoliasearch import AlgoliaIndex

class MyModelIndex1(AlgoliaIndex):
    name = 'MyModelIndex1'
    ...

class MyModelIndex2(AlgoliaIndex):
    name = 'MyModelIndex2'
    ...
...
```
2) Then define your model meta index which will aggregate all the indexes you want to use with your model
```
from django.contrib.algoliasearch import AlgoliaIndex

class MyModelMetaIndex(AlgoliaIndex):
    model_index = []

    def __init__(self, model, client):
        self.model_index = [
            MyModelIndex1(model, client),
            MyModelIndex2(model, client),
            ...
        ]

    def update_obj_index(self, instance):
        for indexer in self.model_index:
            indexer.update_obj_index(instance)

    def delete_obj_index(self, instance):
        for indexer in self.model_index:
            indexer.delete_obj_index(instance)

    def raw_search(self, query='', params={}):
        res = {}
        for indexer in self.model_index:
            res[indexer.name] = indexer.raw_search(query, params)
        return res

    def set_settings(self):
        for indexer in self.model_index:
            indexer.set_settings()

    def clear_index(self):
        for indexer in self.model_index:
            indexer.clear_index()

    def reindex_all(self, batch_size=1000):
        for indexer in self.model_index:
            indexer.reindex_all(batch_size)
```
3) Finally register your MetaIndex to Algolia
```
from django.contrib import algoliasearch
algoliasearch.register(MyModel, MyModelMetaIndex)
```

**Comment by dethi** [comment]
I will close the issue after adding this to the documentation!

**Comment by baltamar3** [comment]
from django.contrib.algoliasearch import AlgoliaIndex module no fount why?
