### ISSUE TITLE
Support multiple geolocations per record 

### ISSUE THREAD

**Issue by PLNech** [algolia/algoliasearch-django#240]
Reported by Jason from a customer :
> Looks like you already support multiple geolocations per record (https://www.algolia.com/doc/guides/searching/geo-search/#adding-geo-info-to-records), but it looks like the feature is lacking from your Django integration (https://github.com/algolia/algoliasearch-django#geo-search). We would need the ability to the multiple geolocations feature with the Django integration.

**Comment by m-vdb** [comment]
FYI I already use multiple geolocations with `algoliasearch-django` in production. You simply have to put a list of locations in `geo_field` and that works.

**Comment by PLNech** [comment]
@m-vdb: Thanks for this feedback! We'll document this in the readme.

@julienbourdeau: I added the missing `Documentation` tag for issues that can be resolved by better documenting existing functionality. I believe it will make sense for all our clients/integrations.
