### ISSUE TITLE
possible to set replica settings in config?

### ISSUE THREAD

**Issue by jaredmcdonald** [algolia/algoliasearch-django#273]
hello! i know it's possible to configure replicas in the index settings, but is there a way to configure settings on those replicas declaratively?

i.e., is there a algoliasearch-django equivalent of this:

```js
products_by_price_asc.setSettings({
  ranking: [
    "asc(price)",
    "..."
  ]
});
```

(from https://www.algolia.com/doc/guides/ranking/sorting/#algolia-replica-indices)

thanks! let me know if i can clarify in any way.

**Comment by nunomaduro** [comment]
Hi @jaredmcdonald,

There is no equivalent of `setSettings` in replicas the `algoliasearch-django`. A workaround may be to override the `set_settings` method on your AlgoliaIndex:
```python
class MyModelIndex1(AlgoliaIndex):
    name = 'MyModelIndex1'

    # ...

    def set_settings(self):
        super(MyModelIndex1, self).set_settings()

        # Code similar to (workaround):
        client = algoliasearch.Client("YourApplicationID", 'YourAPIKey')
        index = client.init_index('your_replica_name')
        index.set_settings({"customRanking": ["desc(followers)"]})
```

What do you think? 👍

**Comment by alexanderatallah** [comment]
@nunomaduro This looks helpful! Looks like we could iterate through each replica, init a new index for each one, and save per-replica rankings

**Comment by nunomaduro** [comment]
Exacly!

**Comment by watsonhaw5566** [comment]
@alexanderatallah 
@nunomaduro 

Hello，How can i use "MyModelIndex1"  is My Django View.

I wannt to using diffrent replica_name to sored my index ranking.

My code now like that.
```python 
 # index.py
 class MyModelIndex1(AlgoliaIndex):
    name = 'MyModelIndex1'
    # ...
    def set_settings(self):
        super(MyModelIndex1, self).set_settings()

        # Code similar to (workaround):
        client = algoliasearch.Client("YourApplicationID", 'YourAPIKey')
        index = client.init_index('your_replica_name')
        index.set_settings({"customRanking": ["desc(followers)"]})
register(MyModel, MyModelIndex1)
 # view.py
 class MyIndexView(View):
    def get(self,request):
    return response = raw_search(MyModel, serializers.validated_data['keyword'], params)
```
I'm using another 'replica_name_index' but not work.

so i wanna asking you how to do that .Thanks your very much.
