### ISSUE TITLE
Support `Django 2.2 LTS`

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-django#287]
Django 2.2 is its newest Long Term Support release and we haven't tried this package with it yet.

**Actions**: Test this package with Django 2.2, performs the code adjustments, and upgrade the test suite to test against all django versions.

**Comment by pbx** [comment]
Thanks for creating this issue.

**Comment by tkrugg** [comment]
Hey @chloelbn I've been spending sometime today on this topic, and was able to verify that the Django integration works correctly on 2.2 LTS.
I'd like to make sure I'm not missing any specifics features: is there somewhere a list of things I need to go through to make I'm not missing anything.

cc @algolia/api-clients-squad

**Comment by pbx** [comment]
FWIW we're successfully running the latest version of this package under Django 2.2 at @masschallenge.

**Comment by tkrugg** [comment]
thanks for confirming @pbx I guess the next step is just to update the test suite and close this issue :)
