### ISSUE TITLE
Support SQL View based Facade Models to Trigger Auto Sync

### ISSUE THREAD

**Issue by tusharsrivastava** [algolia/algoliasearch-django#288]
- Django version: 1.10.8
- Algolia Django integration version: 1.5.1
- Algolia Client Version: 1.14.1
- Language Version: 3.6.6

### Description
I have created a SQL View which joins the data as per requirement of Algolia Indexing. I need to know how will Algolia Index Sync whenever the data in one of the contributing model is added, updated, or deleted. Do I've to manually trigger it from a signal or will it be managed automatically.

**Comment by tkrugg** [comment]
Hi @tusharsrivastava 
IIUC, you have gathered your data to index into an SQL view and now want that data to automatically sync to your Algolia Index.  

Django does not have support for SQL views. For this reason, `algoliasearch-django` cannot provide support for it. 

You can of course [trick it into using a view by creating a fake model and quitly changing the migration files to create/delete the view accordingly](https://resources.rescale.com/using-database-views-in-django-orm/). You'll be fighting the framework, I wouldn't vouch for it. 

In your case, I would simply create a signal listening to CRUD on each of the contributing models, then trigger a reindex from there.

```py
from algoliasearch_django import save_record

@receiver(post_save, sender=Model1)
@receiver(post_save, sender=Model2)
@receiver(post_save, sender=Model3)
def reindex(sender , **kwargs)
    // fetch model instance
    instance = ...
    save_record(instance)
```
I hope this helps. Closing this for now, feel free to reopen if you'd like to further discuss.
