### ISSUE TITLE
Django ORM query optimisations

### ISSUE THREAD

**Issue by viperfx** [algolia/algoliasearch-django#290]
- Django version: Django==2.2.8
- Algolia Django integration version: algoliasearch-django==1.7.1
- Algolia Client Version: algoliasearch==1.20.0
- Language Version: english

### Description
The `rebuild_index` script is creating many queries when building the index.

The following stats were observed when profiling queries:

When testing locally, an Index with local fields on the same model (No FK or M2M enabled) in fields.

1 query for 35 records (as expected since local fields)

When FK fields were enabled (no M2M on model):

Using the `get_queryset` method, `selected_related` and `iterator` was added. to speed things up.

376 queries for 35 records (using select_related)
481 queries without select_related 

I expect the `select_related` to save a lot more queries. But it's not? 

The library asks us to put all fields on model methods - but is there something happening different where the Django ORM cannot optimize these queries with the way the library internals work?

When indexing large sets of records, the process can easily run out of memory.

**Comment by PLNech** [comment]
Hi @viperfx, thanks for sharing this!

Unfortunately, we don't have anymore the resources to develop further this integration. We're keeping it online for reference, but are now focusing our efforts on the [Python API Client](https://www.algolia.com/doc/api-client/getting-started/install/python/?language=python). 
Considering your setup, the best option might be to use this client and implement the indexing on your side: it will likely be simpler to optimize the associated queries to your specific needs.

**Comment by viperfx** [comment]
Oh I see - that is really disappointing to hear, especially after investing time into setting it up. Please consider adding a note at the top of the README about this. I have only spent a small amount of time to figure out this library is not a good fit for production, for others it may take a lot longer.

I will look into the python client. Is there a resource guide on creating an indexer script?

It would be really good if there was a migration guide from Django users to using the python API client.

**Comment by nunomaduro** [comment]
@viperfx I am sorry for that. You are going to address your feedback on the next couple of months making the readme and your documentation clear how the deprecation of this integration.

On the time of this writing, there is no guide that combines Django with our Python API Client.

But you can refer to the Python API Client documentation to get some tips on how index your data with Algolia: [algolia.com/doc/api-client/methods/indexing/](https://www.algolia.com/doc/api-client/methods/indexing/.).

Let me know how it goes and if you have more questions.
Best regards,
