### ISSUE TITLE
disable indexing decorator not working

### ISSUE THREAD

**Issue by dbinetti** [algolia/algoliasearch-django#296]
- Django version: 3.1
- Algolia Django integration version: 1.7.1
- Algolia Client Version: 1.20.0
- Language Version: 

### Description
The @disable_auto_indexing decorator does not appear to work.

### Steps To Reproduce

Use the @disable_auto_indexing on a function.  

Expect: No reindexing

Get:  Indexing.  

--
This one hurts, because it cost me $100 to reindex fields that didn't need to be indexed...

**Comment by tkrugg** [comment]
Hi @dbinetti, thanks for reporting this issue. Are you able to provide a sample of the code you've used it on?

What I can say is that this decorator [has a test](https://github.com/algolia/algoliasearch-django/blob/ce9447c6a45749f55b48f27bb1c4d58710ce480a/tests/test_decorators.py#L16) that isn't failing when tested on python 3.6 and django 3.1: https://travis-ci.org/github/algolia/algoliasearch-django/jobs/748217497

I think it might be that the model you've used it on was not registered, or that the indexing in your specific case was not performed via the post_save receiver. A code sample would definitely help me troubleshoot.

**Comment by dbinetti** [comment]
Been five months and I've left the project, so I'm afraid I can't help.  Closing.
