### ISSUE TITLE
How to sorted replicas_index  dynamic？

### ISSUE THREAD

**Issue by watsonhaw5566** [algolia/algoliasearch-django#300]
- Django version: Django 2.2
- Algolia Django integration version: algoliasearch-django1.7.2
- Algolia Client Version: 1.20.0
- Language Version:Python3.7.4

### Description
I don't know how to sort my replicas_index result.I find the issues,just find that [issues273](https://github.com/algolia/algoliasearch-django/issues/273).
But that way need each time to used `manage algolia_applysettings` just can work.
It's don't dynamic.I wanna the frontend partner post sort params to mine and I to using different replicas_index to show the search result.
Have somebody can help me how to do.Thanks,love the Algolia Django.

**Comment by tkrugg** [comment]
Hi @watsonhaw5566 sounds like you just need to do it from your Algolia Dashboard. 
Have you tried following theses steps ? https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/creating-replicas/#using-the-dashboard

**Comment by watsonhaw5566** [comment]
> Hi @watsonhaw5566 sounds like you just need to do it from your Algolia Dashboard.
> Have you tried following theses steps ? https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/creating-replicas/#using-the-dashboard

THanks，I solved the problem

**Comment by tkrugg** [comment]
Glad you did @watsonhaw5566 I'll close this issue then.
