### ISSUE TITLE
algoliasearch v1.20.0 still targeted as a dependency

### ISSUE THREAD

**Issue by nwarchitect** [algolia/algoliasearch-django#308]
- Django version: 3.1.1
- Algolia Django integration version: 1.7.3
- Algolia Client Version: 1.20.0
- Language Version: 3.8

### Description

Installing _algoliasearch-django_ in its latest version (1.7.3) will install _algoliasearch_ in its 1.20.0 version.
This version seems outdated and the API docs target v2.x.

I saw that the requirements.txt was updated to include the latest major version (https://github.com/algolia/algoliasearch-django/commit/4ffda5a4a12a1fdd5073181b75e8c2239373de8b) of _alogliasearch_. Nevertheless, the _setup.py_ file still depends on v1.7.x.

Will you update this shortly?

Thanks for your feedback.

### Steps To Reproduce

`pip install --upgrade 'algoliasearch-django>=1.7.1,<2.0'`
and algoliasearch will be installed in its 1.20.0 version.

**Comment by tkrugg** [comment]
Hi @nwarchitect yes, my bad, there was a little bit more to do. Sorry about the confusion.
There is a ongoing PR #306 fixing this.

**Comment by tkrugg** [comment]
This is now fixed! @nwarchitect sorry for the delay.
