### ISSUE TITLE
Auto indexing when related model is changed

### ISSUE THREAD

**Issue by EnriqueSoria** [algolia/algoliasearch-django#309]
- Django version: _any_
- Algolia Django integration version: _any_
- Algolia Client Version: _any_
- Language Version: _any_

### Description
Is there a way to auto index when a related object is modified, or it has to be done manually (via post_save or something)?

For example:
```python
class Product(models.Model):  
    ...
    
class Price(models.Model):
    product = models.ForeignKey(Product, ...)
```

In this example I would like to get `Product` indexed when I change one of it's `prices`.

**Comment by tkrugg** [comment]
Hi @EnriqueSoria, that should work if you explicitly call `.save()` on both models.

```py 
# update price
price.value = 10.0
price.save() 

# notify algolia index
price.product.save()
```

This is simple enough, but if you don't want to uselessly trigger a request to your database, here is how to do it:

```py
# update price
price.value = 10.0
price.save() 

# trigger a reindexing of product
import algoliasearch_django as algoliasearch
index_adapter = algoliasearch.get_adapter(Product)
adapter.save_record(price.product)
```


we should probably add a shortcut method, something along theses lines:

```py
import algoliasearch_django as algoliasearch, 

def reindex(instance):
   Model = instance.__class__
   index_adapter = algoliasearch.get_adapter(Model)
   index_adapter.save_record(instance)
```

**Comment by EnriqueSoria** [comment]
It would be great to add the option to define which models trigger a reindexation for an index

As for the shortcut method, can't we just use `save_record`?
```
import algoliasearch_django
algoliasearch_django.save_record(instance)
```

**Comment by tkrugg** [comment]
You are absolutely right. That should work perfectly.
