### ISSUE TITLE
Django algolia search: How to create search for multiple models

### ISSUE THREAD

**Issue by sant527** [algolia/algoliasearch-django#319]
In Django I have 4 different models

```
class Baby(model.Model):
    name = ... #(babys name)
    description = ...
    .... other fields not common

class BabyStore(model.Model):
    name = ...  #(name of the shop)
    description = ...
    .... other fields not common

class BabySitter(model.Model):
    name = ... #(babysitter name)
    description = ....
    .... other fields not common

class BabyDoctor(model.Model):
    name = ... #(babydoctors name)
    description = ...
    .... other fields not common
```

As per https://github.com/algolia/algoliasearch-django we have to register each model

```
import algoliasearch_django as algoliasearch

from .models import YourModel

algoliasearch.register(YourModel)
```

This will create seperate index for each model.

In my case i want to have a search UI for all of them together and use the model as the facet.

eg:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/TZGRV.png

So how to use multiple indexes and create a single search

I know within each index, we can have facets. But here Along with that i want to use each index as a facet itself

**Comment by tkrugg** [comment]
I'll close this issue. Happy to investigate this again after you elaborate on the problem you're facing with my approach. Feel free to reopen then.
