### ISSUE TITLE
Add support for Django 4.x series

### ISSUE THREAD

**Issue by ryancausey** [algolia/algoliasearch-django#333]
- Django version: 4.x
- Algolia Django integration version: 3.0.0
- Algolia Client Version: 3.0.0
- Language Version: Python 3.8+

### Description

This library indicates it only supports Django up to the 3.x series. Django 4.2 LTS has already been released with LTS support through the beginning of 2026, and the first Django 5.x series is slated to drop in the beginning of 2024. Please add support for Django 4.x.

The release schedule can be seen under the "Supported Versions" header of this page: https://www.djangoproject.com/download/

**Comment by exiao** [comment]
+1

**Comment by tpotjj** [comment]
+1
