### ISSUE TITLE
django-algolia project

### ISSUE THREAD

**Issue by Kmaschta** [algolia/algoliasearch-django#6]
Hi,

Since two months, I am working on a Django version of Algolia client.
His goal is simple: index (on the fly like [haystack](http://haystacksearch.org/)) the models that has a specified setting, allow to search by model and consume responses very easily.

```python
class MyPony(models.Model):
  ALGOLIA_INDEX_FIELDS = ('name', 'clogs_number',)

  name = models.CharField(max_length=255)
  clogs_number = models.IntegerField()
```

```bash
./manage.py rebuild_algolia_index --model=MyPony
```

```python
>>> import algolia
>>> from my.project.models import MyPony

>>> algolia.search(MyPony, 'Raibow')
AlgoliaResult({'count': 1, 'instances': [<MyPony: Rainbow Dash>], 'model': <class 'my.project.models.MyPony'>, 'page': '1/1'})
```

With a little bit of features like pagination, for work with Django Rest Framework.

```python
import algolia
from algolia.pagination import Paginator as AlgoliaPaginator
from rest_framework import generics

class MyPonySearch(generics.ListAPIView):
    model = MyPony
    serializer_class = MyPonySerializer
    paginator_class = AlgoliaPaginator

    def get_queryset(self):
        return algolia.search(MyPony, self.requests.get('q', ''))
```

You can see all of that in the develop branch of my repo : https://github.com/Kmaschta/django-algolia/tree/develop
(the documentation is not up-to-date)

I learn with joy that you start to make an official Django lib!
But my work becomes obsolete, and work our separate ways is against-productive.

How can we ensure to collaborate about that?

**Comment by dethi** [comment]
Hi,

Happy to learn that you have build an extension :+1: . As I see, there is some majors differences between the two projects. But I'm sure we can collaborate together!
Maybe we can organize a call/skype/chat/whatever to discuss about your expectation, collaboration, etc.
What do you think?

**Comment by Kmaschta** [comment]
I'll send you an email soon, I can't wait to start. :ok_hand:
